<?php
// p2 ースタイル設定
// for edit_conf_user.php

echo <<<EOSTYLE
<style type="text/css" media="all">
<!--

p#pan_menu{
	border-bottom: solid 1px #ccc;
}

table#edit_conf_user{
	border: solid 1px #ccc;
}

table#edit_conf_user td{
	padding: 4px;
	margin: 4px;
	border: solid 0px;
	border-right: solid 1px #efefef;
	border-bottom: solid 1px #efefef;
}

tr.group{
	background-color: #efefef;
}

-->
</style>
EOSTYLE;

?>