<?php
// p2 ースタイル設定
// for setting.php

?>
body,td{
	font-size: <?php echo $STYLE['fontsize'] ?>;
}

p#pan_menu{
	border-bottom: solid 1px #ccc;
}

ul#setting_menu{
	padding:6px 16px 6px 16px;
}

p#client_status{
	padding:12px;
	border:solid 1px #ccc;
}
<?php

/*
 * Local Variables:
 * mode: php
 * coding: cp932
 * tab-width: 4
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * End:
 */
// vim: set syn=php fenc=cp932 ai et ts=4 sw=4 sts=4 fdm=marker:
