<?php
/**
 * rep2expack - ユーザー定義スタイル初期化ファイル
 */

$STYLE = array(
    'a_underline_none' => null,
    'acolor' => null,
    'acolor_h' => null,
    'acolor_v' => null,
    'background' => null,
    'bgcolor' => null,
    'conf_b_color' => null,
    'conf_b_style' => null,
    'conf_b_width' => null,
    'conf_btn_background' => null,
    'conf_btn_bgcolor' => null,
    'fav_color' => null,
    'fontfamily' => null,
    'fontfamily_bold' => null,
    'fontsize' => null,
    'fontstyle_bold' => null,
    'fontweight_bold' => null,
    'form_fontsize' => null,
    'infowin_fontsize' => null,
    'menu_background' => null,
    'menu_bgcolor' => null,
    'menu_cate_color' => null,
    'menu_color' => null,
    'menu_fontsize' => null,
    'menu_ita_color' => null,
    'menu_ita_color_h' => null,
    'menu_ita_color_v' => null,
    'menu_newres_color' => null,
    'menu_newthre_color' => null,
    'read_acolor' => null,
    'read_acolor_h' => null,
    'read_acolor_v' => null,
    'read_background' => null,
    'read_bgcolor' => null,
    'read_color' => null,
    'read_fontsize' => null,
    'read_mail_color' => null,
    'read_mail_sage_color' => null,
    'read_name_color' => null,
    'read_newres_color' => null,
    'read_ngword' => null,
    'read_thread_title_color' => null,
    'respop_b_color' => null,
    'respop_b_style' => null,
    'respop_b_width' => null,
    'respop_background' => null,
    'respop_bgcolor' => null,
    'respop_color' => null,
    'respop_colorrespop_color' => null,
    'respop_fontsize' => null,
    'sb_acolor' => null,
    'sb_acolor_h' => null,
    'sb_acolor_v' => null,
    'sb_background' => null,
    'sb_bgcolor' => null,
    'sb_color' => null,
    'sb_fontsize' => null,
    'sb_newres_color' => null,
    'sb_now_sort_color' => null,
    'sb_order_color' => null,
    'sb_tacolor_h' => null,
    'sb_tbackground' => null,
    'sb_tbackground1' => null,
    'sb_tbgcolor' => null,
    'sb_tbgcolor1' => null,
    'sb_th_background' => null,
    'sb_th_bgcolor' => null,
    'sb_thre_title_new_color' => null,
    'sb_tool_acolor' => null,
    'sb_tool_acolor_h' => null,
    'sb_tool_acolor_v' => null,
    'sb_tool_background' => null,
    'sb_tool_bgcolor' => null,
    'sb_tool_border_color' => null,
    'sb_tool_color' => null,
    'sb_tool_newres_color' => null,
    'sb_tool_sepa_color' => null,
    'sb_ttcolor' => null,
    'textcolor' => null,
    'thre_title_color' => null,
    'thre_title_color_h' => null,
    'thre_title_color_v' => null,
);

/*
 * Local Variables:
 * mode: php
 * coding: cp932
 * tab-width: 4
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * End:
 */
// vim: set syn=php fenc=cp932 ai et ts=4 sw=4 sts=4 fdm=marker:
